name: Recreate webhooks

# This recreates webhooks for the Pact Broker service twice an hour using a generated token. This
# token will only be valid for 1 hour so this runs every 30 minutes.

on:
  schedule:
    # At minute 0 and 30 past every hour from 8 through 20
    - cron: 0,30 7-20 * * *


jobs:
  apply_webhooks:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Get app token
        id: get_workflow_token
        uses: actions/create-github-app-token@f8d387b68d61c58ab83c6c016672934102569859 # v3.0.0
        with:
          skip-token-revoke: 'true'
          app-id: ${{ vars.LAA_JAVA_SERVICE_DEPLOYER_APP_ID }}
          private-key: ${{ secrets.LAA_JAVA_SERVICE_DEPLOYER_KEY }}
          owner: 'ministryofjustice'
          permission-actions: write
      - name: Authenticate to the cluster
        uses: ./.github/actions/authenticate-cluster
        with:
          kube_cluster: ${{ secrets.KUBE_CLUSTER }}
          kube_cert: ${{ secrets.KUBE_CERT }}
          kube_token: ${{ secrets.KUBE_TOKEN }}
          kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      - name: Make create-webhooks.sh executable
        run: chmod +x ./seed/create-webhooks.sh
      - name: Apply webhooks
        env:
          NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}
          GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: ./create-webhooks.sh
        working-directory: ./seed
